# Generated by Django 3.1.2 on 2020-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoloduleReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='最終更新日時')),
                ('channel_code', models.CharField(max_length=20, unique=True, verbose_name='チャンネルID')),
                ('channel_name', models.CharField(max_length=2000, verbose_name='チャンネル名')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ohayou',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成日時'),
        ),
        migrations.AddField(
            model_name='ohayou',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最終更新日時'),
        ),
    ]
