# Generated by Django 3.1.2 on 2020-10-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20201030_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holodulereminder',
            name='id',
        ),
        migrations.AlterField(
            model_name='holodulereminder',
            name='channel_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='チャンネルID'),
        ),
    ]
